name: sharpshooter
title: sharpshooter
version: '1.2.7'
summary: Minimal file manager
description: minimal terminal application that in a single key press lets you navigate and copy/cut/delete/(un)zip your files and open the terminal
type: app
icon: img/sharpshooter_logo_512.png

grade: devel
confinement: devmode
base: core18

parts:
  sharpshooter:
    plugin: python
    python-version: python3
    python-packages:
      - pathlib
    source: https://github.com/vs-slavchev/sharpshooter.git
    stage-packages:
      - python-six

apps:
  sharpshooter:
    command: bin/sharpshooter
