name: sharpshooter
title: sharpshooter
version: '1.0.2'
summary: Minimal file manager
description: minimal terminal application that in a single key press lets you navigate and copy/cut/delete/archive your files and open the terminal
type: app
icon: img/sharpshooter_logo_512.png

grade: devel
confinement: devmode
base: core18

parts:
  sharpshooter:
    plugin: python
    source: https://github.com/vs-slavchev/sharpshooter.git
    stage-packages:
      - python-six

apps:
  sharpshooter:
    command: bin/sharpshooter
